[project]
name = "pro2"
version = "0.1.0"
description = "Pantyflows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agentops>=0.3.23",
    "crewai>=0.95.0",
    "crewai-tools>=0.25.8",
]
